# Generated by Django 4.2.5 on 2023-10-16 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_InsightSphere', '0003_channelmessage_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelMessage',
        ),
    ]
